apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ros2-driver
  namespace: devices
spec:
  serviceName: ros2-driver
  replicas: 1
  selector:
    matchLabels:
      app: ros2-driver
  template:
    metadata:
      labels:
        app: ros2-driver
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: ros2-driver
          image: ros2-driver:v1
          imagePullPolicy: Never
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - containerPort: 5000
          env:
            - name: ROS_DOMAIN_ID
              value: "0"
             - name: RMW_IMPLEMENTATION
              value: rmw_fastrtps_cpp
            - name: FASTRTPS_DEFAULT_PROFILES_FILE
              value: /etc/fastdds/fastrtps_profile.xml
            - name: ROS_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: ROS_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PYTHONPATH
              value: "/opt/ros/humble/lib/python3.10/site-packages:/ros2_ws/install/lib/python3.10/site-packages"
            - name: LD_LIBRARY_PATH
              value: "/opt/ros/humble/lib:/ros2_ws/install/lib"
            - name: ROS_ROOT
              value: "/opt/ros/humble/share/ros"
            - name: ROS_PACKAGE_PATH
              value: "/opt/ros/humble/share:/ros2_ws/src"
            - name: ROS_DISTRO
              value: "humble"
          volumeMounts:
            - name: fastdds-profile
              mountPath: /etc/fastdds
              readOnly: true
          command: ["/bin/bash"]
          args: ["-c", "source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash && ros2 launch ros2_driver driver.launch.py"]
      
      volumes:
        - name: fastdds-profile
          configMap:
            name: fastrtps-profile

---
apiVersion: v1
kind: Service
metadata:
  name: ros2-driver
spec:
  selector:
    app: ros2-driver
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: NodePort
  externalIPs:
    - 192.168.31.118
